name: UPM on npsjs.com
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish --access public
      working-directory: Packages/com.danielshervheim.unity-core
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
